import 'mdb-react-ui-kit/dist/css/mdb.min.css'
import "@fortawesome/fontawesome-free/css/all.min.css"
import { Inter } from 'next/font/google'
import './globals.css'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

import Header from '@/component/header/haeder'
// import Heading from '@/component/heading-component/heading'

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressContentEditableWarning={true}>
        <Header/>
        {children}
        {/* <Header>
          {children}
        </Header> */}
        </body>
    </html>
  )
}
